jobs:
  - name: System uptime
    command: uptime
    interval:
      seconds: 15

  - name: Memory and Swap Usage
    command: free -h
    interval:
      minutes: 1
      seconds: 30

  - name: Active Network Connections
    command: ss -tunap
    interval:
      hours: 24
